### ISSUE TITLE
Share Initial Findings Summary for Reports Site

### ISSUE THREAD

**Issue by acouch** [cal-itp/reports#130]
**Background**

The reports team has interviewed a number of stakeholders and agencies in order to evaluate improvements to the reports.calitp.org site.

While the reports team will continue to solicit feedback about the reports site from agencies, they are prepared to share a summary of their initial findings.

The reports team are preparing a draft now, and will be prepared to share a final version by May 20.

**Comment by holly-g** [comment]
Slide deck: https://docs.google.com/presentation/d/1w0hfUpTe-hwTW-6zQfMq0NYy8sHKKktCB-FWHI9fUs8/edit#slide=id.p
