### ISSUE TITLE
Adding development-build as a viewable branch in netfliy

### ISSUE THREAD

**Issue by machow** [cal-itp/reports#15]
@thekaveman, do you mind working your netlify magic, to have it deploy a preview of the development-build branch on this repo? I can set the action so a development branch pushes content there. Link doesn't have to be pretty!

**Comment by thekaveman** [comment]
@machow added a deploy context to Netlify for that branch:

![image](https://user-images.githubusercontent.com/1783439/123689961-b3094800-d808-11eb-94a1-9b5801f92629.png)

Once we have the branch in the repo it will kick off an initial build, and I can give you the (stable) URL.

**Comment by thekaveman** [comment]
Also just a heads up, we get free deploy previews for any PR against both the production branch, and any branch deploy branches:

![image](https://user-images.githubusercontent.com/1783439/123691282-455e1b80-d80a-11eb-875e-0c24ccbb8bb2.png)

**Comment by machow** [comment]
Ah cool--thanks! That's perfect, I figure we'll have development-build that can preview w/o a PR, and then it's nice to have the option to open PRs that are content builds!

**Comment by machow** [comment]
seems to be working! (going to push updated version up in a sec..)

https://development-build--cal-itp-reports.netlify.app/
