### ISSUE TITLE
Use full month names

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/reports#150]
The site currently uses abbreviations such as "Apr" or "Jun" on [index pages](https://reports.calitp.org/gtfs_schedule/2022/04/) as well as individual [reports](https://reports.calitp.org/gtfs_schedule/2022/04/300/index.html). This looks a little strange, and I think we have the space for full month names.

**Describe the solution you'd like**
Site displays full month names, like "June" instead of abbreviations like "Jun"

**Comment by holly-g** [comment]
Resolved by https://github.com/cal-itp/reports/pull/157
