### ISSUE TITLE
Re-Examine which Agencies we use for monthly GTFS Reports 

### ISSUE THREAD

**Issue by Nkdiaz** [cal-itp/reports#153]
**Is your feature request related to a problem? Please describe.**
Every month we generate GTFS Quality reports that we then email out to various agencies. Of all of the agencies we have access to their feed information,  63 of them are tagged as `use_for_report = false` in the table `cal-itp-data-infra.views.reports_gtfs_schedule_index`. Several of the agencies in the list are large agencies who could benefit from receiving a monthly quality report. 

**Describe the solution you'd like**
We should re-examine why certain agencies have use_for_report = false and see if we can add some of them to the list of agencies we do email out. 

**Describe alternatives you've considered**

**Additional context**
The query used to find the list of agencies in BigQuery is as follows:
``SELECT distinct agency_name FROM `cal-itp-data-infra.views.reports_gtfs_schedule_index` Where use_for_report = false``

**Comment by Nkdiaz** [comment]
Currently looking in reports_gtfs_schedule_index:
the `use_for_report` is True if a feed has 3 things
1- calitp_url_number = 0
2- has_feed_info = True
3- Is not a private feed

In addition, we are hardcoding certain feeds as private to make sure that reports are generated for them -calitp_ids 13(Amtrack) and 346(Tulare county area transit). 
This leads to several questions: 
Are there any feeds with a url_number other than 1 that we want to generate reports for?
What constitutes as a private feed?
Within our tables, only Amtrack and Tulare are the only ones we have marked for private feeds. So is this still necessary?

**Comment by Nkdiaz** [comment]
Worth mentioning that there is an old metabase dashboard that displays many of the things i mentioned above.
https://metabase.k8s.calitp.jarv.us/collection/67-reports-calitp-org

**Comment by lauriemerrell** [comment]
I would defer to @edasmalchi on this but a few stray thoughts:

* I think we may want to figure out ways to make `feed_info` optional here, especially as we have seen a few agencies that have moved from feeds with feed_info to feeds without. (This would require a refactor of data used in the report, so defer to Eric on prioritization etc.)
* `calitp_url_number` will ideally be deprecated in favor of actually using the `primary` / `precursor` feed flags as part of the GTFS schedule pipeline refactor. So I would probably not worry too much about that for right now.
* For private feeds, I would check in with other folks within Cal-ITP, I would default to not changing without explicit guidance from MSD / Assessments / related stakeholders

**Comment by e-lo** [comment]
> we have seen a few agencies that have moved from feeds with feed_info to feeds without

@lauriemerrell do we have a link to find out who these are? Have we reached out to any of them yet @evansiroky @o-ram to know why they have? My guess would be that they have moved to using a feed created by a CAD/AVL vendor.  I think asking the CAD/AVL vendor to include feed_info might be an option.

**Comment by lauriemerrell** [comment]
@e-lo yes sorry I am referring to @o-ram's comment here: https://github.com/cal-itp/data-infra/issues/1184#issuecomment-1148063333 for the `feed_info` changes.

Definitely agree that getting the files would be good, but I also think we shouldn't have presence of `feed_info` as a blocker to generating reports (right now, we *can't* generate a report if they don't have `feed_info` -- I think we should try to change that as a technical requirement, but obviously having `feed_info` is preferred!)

**Comment by edasmalchi** [comment]
Short-term I think making `feed_info` optional is the way to go. I should be able to sort that out with regards to the warehouse tables+report generation itself before the next reports cycle.

Will also try asking one of the vendors since I probably have a good contact.
