### ISSUE TITLE
Refactor tbl_file_check in reports.ipynb

### ISSUE THREAD

**Issue by Nkdiaz** [cal-itp/reports#156]
**Describe the bug**
As part of the ongoing effort to update/refactor the GTFS quality reports, we are looking at various ways to simplify the reports.ipynb that is used to generate the monthly reports.  One of the areas identified is `tbl_file_check` that is used to check for the presence or absence of different types of files which is then used to populate `4_file_check.json`. 

**To Reproduce**
`tbl_file_check` has a distinctive use of a green checkmark that is `\u2705"` that then populates the JSON file 

**Additional context**
part of an ongoing work to speed up the gtfs_quality report generation

**Comment by acouch** [comment]
Closing as this the [checkmark in question](https://github.com/cal-itp/reports/blob/main/reports/generate_reports_data.py#L148) doesn't appear to have a significant effect on the reports generation speed. The ✅ does not take up much more space than a boolean.
