### ISSUE TITLE
User Story: Information Organized by Vendor

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/reports#181]
### Summary

As a transit agency, Cal-ITP team member, or other interested party, I want to see information and metrics organized by vendor on reports.calitp.org so that I can make informed decisions on vendor selection and see the level of service received by others with my current vendor in order to effectively manage relationships and deliver the best data possible to transit riders.

### Acceptance Criteria

1. When viewing pages such as [this monthly index](https://reports.calitp.org/gtfs_schedule/2022/07/), it is possible to group/filter the report links by vendor(s) used (drop-down bar with vendor info)
1. When viewing [individual reports](https://reports.calitp.org/gtfs_schedule/2022/07/300/index.html), vendor names and associated information are prominently displayed, including multiple vendors as appropriate (for example, agency uses a different vendor for GTFS static vs. RT)
~~2. A separately formatted report is available for each vendor, summarizing the number of agencies using that vendor as well as data quality and performance metrics as appropriate.~~

### Notes

Data is tracked in Transit Technology Stacks Airtable base.

This has been a very common request from agencies and Cal-ITP/Caltrans staff.

### Tester [Stakeholder]

1. @edasmalchi 
2. @o-ram (optional)

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
3. - [ ] Team understands acceptance criteria
4. - [ ] Team has defined solution / steps to satisfy acceptance criteria
5. - [ ] Acceptance criteria is verifiable / testable
6. - [ ] External / 3rd Party dependencies identified

**Comment by acouch** [comment]
We've discussed something like this as a way of filtering vendors. Would not be filtered as a default:
![image](https://user-images.githubusercontent.com/512243/192844025-64793ce0-8390-47c7-aab6-e5eae05d8d75.png)

**Comment by acouch** [comment]
Part of this ticket is the prep needed to look into the warehouse data to make sure that all of the agencies have a vendor associated with them.

**Comment by edasmalchi** [comment]
Or more specifically which product definitions in airtable we're interested in and whether enough have meaningful vendor info -- threshold is probably more like 60-80% than 100%
