### ISSUE TITLE
Update to new Warehouse

### ISSUE THREAD

**Issue by acouch** [cal-itp/reports#193]
**Background**

This is a placeholder ticket to capture the conversation about updating to the new warehouse.

Some high-level strategies:

1. Do a basically identical replacement
2. We could reconceptualize the "entity" that is being assessed in the reports 

Will update this after internal convo.

**Comment by lauriemerrell** [comment]
Per meeting today (10/4) between @acouch, me, and @edasmalchi:
* Wait for [#1762](https://github.com/cal-itp/data-infra/issues/1762) to be completed
* Update reports site to understand new keying; plan is to try to preserve ITP ID as possible

**Comment by acouch** [comment]
The update is still being QAed. There are two PRs #219 and #222 that are still in progress. Once the QA is finished, and any updates applied, those can be pulled in.
