### ISSUE TITLE
Gillian's revisions to Reports site

### ISSUE THREAD

**Issue by harrisonpeck** [cal-itp/reports#20]
Hi @machow @Nkdiaz @themightychris, 

Gillian has requested some very small tweaks to the text on the Reports website. Her edits are in pink in [this document](https://docs.google.com/document/d/16auZ1yVciIvihZR_6P1H5xdXom_3Mf_jxyYwW-vbzrI/edit?ts=60da80c2#). Please let me know if you have any questions.

Thanks!!
Harrison

**Comment by hunterowens** [comment]
@machow let me know if you want to make these changes otherwise I will open up a PR tonight

**Comment by machow** [comment]
Is this a change we're looking to incorporate for styled reports released Friday (and applied back to May reports)? If so, we can make the changes to the template while finishing it this week!

**Comment by hunterowens** [comment]
I think all the changes were for the homepage rather than the report
itself, but lmk if you spotted anything for the reports.

-Hunter
