### ISSUE TITLE
User Story: Update email copy to announce RT checkmark, speedmaps, agency reports

### ISSUE THREAD

**Issue by JGSchaumburg** [cal-itp/reports#207]
### Summary

1. **As a** transit agency receiving the upcoming monthly report 
2. **I want** to see updated email copy
3. **So that** I know to navigate to the site to see other agency reports, an indicator or RT status, and speedmaps for agencies that have them

[
In user research, we learned that 1) most agencies view their report in the email rather than navigating to reports.calitp.org and 2) agencies didn't know that you could view other agency reports
]

### Acceptance Criteria

1. If I open the reports email for this month:

- I should see updated email copy that prompts me to navigate to reports.calitp.org
- I should see updated email subject line and message copy that announces the RT checkmark, speedmaps, and reports for other agencies

### Tester [Stakeholder]

1. @edasmalchi 

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
2. - [ ] Team understands acceptance criteria
4. - [ ] Team has defined solution / steps to satisfy acceptance criteria
5. - [ ] Acceptance criteria is verifiable / testable
6. - [ ] External / 3rd Party dependencies identified

**Comment by JGSchaumburg** [comment]
@edasmalchi per our conversation earlier this week, here is a ticket for updating the email copy to announce the RT checkmark, speedmaps, and seeing reports for other agencies.    @holly-g @acouch FYSA

**Comment by edasmalchi** [comment]
How about something like this? @o-ram also asked if we could re-announce the published guidelines, so I've included that too.

> All previous reports for your agency, as well as reports for other agencies across California, are available at https://reports.calitp.org/. We've also introduced some design improvements to make the site easier to navigate. We invite you to browse the improved site, and please let us know if you have further design suggestions.
> 
> This version of the reports now includes information on the presence of GTFS Realtime (GTFS-RT) data for your agency. Realtime data contributes to a better rider experience by letting riders know exactly when their bus or train is coming, as well as detour and trip cancellation info. Cal-ITP also archives and analyzes GTFS-RT data across California to produce analyses such as the [California Transit Speed Maps](https://analysis.calitp.org/rt/README.html), a link will be included in your report if applicable.
> 
> We're also pleased to announce that Caltrans and Cal-ITP have finalized and released Version 3 of the California Transit Data Guidelines, check them out [here](https://dot.ca.gov/cal-itp/california-transit-data-guidelines)!
> 
> If you have any questions about GTFS-RT data or your monthly report, please contact us at hello@calitp.org. We're also available to provide support to help your agency produce GTFS-RT if it does not already do so, or any other type of technical support.

**Comment by acouch** [comment]
I've created a PR #208 to include this update.
