### ISSUE TITLE
Swap Postmark Transactional Email Service, for Hubspot

### ISSUE THREAD

**Issue by acouch** [cal-itp/reports#209]
**Background**

As a hubspot user, I want report emails to use Hubspot transactional email service so that the report emails are better integrated into the Hubspot CRM

As a developer, I want clear documentation on how to send the monthly report emails, so that I can send emails out in a timely fashion.

**Acceptance criteria**

- [ ] Update to hubspot is tested and results approved by @edasmalchi and/or @o-ram 
- [ ] There is clear documentation on sending emails using hubspot

**Comment by AnthonyRollins** [comment]
@acouch We need to upgrade the account to give you the tokens you need. Are you able to put together an estimate without those details? We are still working on budgets here, so we won't be able to upgrade service and prefer to understand the estimate before needing to upgrade.

**Comment by acouch** [comment]
@AnthonyRollins as I noted in slack, I am ready to do the upgrade as soon as you are able to provide a token. I would estimate a half day of work or less on my end, with a couple of day turn-around given my allocation to the project. I look forward to working on this, once things are setup on your end. Thanks!

**Comment by thekaveman** [comment]
Shared Hubspot API token information with @acouch

**Comment by acouch** [comment]
@thekaveman

We started a PR for this.

A couple of notes:

1. The hubspot workflow requires a [template email to be created in the Hubspot UI](https://developers.hubspot.com/docs/api/marketing/transactional-emails#single-send-api) first, before an email is sent. To test the hubspot integration we would need to get a test email template setup, or give @charlie-costanzo access to create a test email template. It looks like this will change the workflow a little as the emails templates would be created in the Hubspot UI and then sent from the local developers computer. With PostMark the template is created locally in code. This could potentially be a more efficient workflow, as non-devs could update the email template.
2. In the current implementation with PostMark, we have a development server that we send test emails through. We could continue a similar practice if there is a development or sandbox API to test with. The test emails are only sent internally, so it would not mess up your metrics most likely if you don't have a non-production API token.
3. This does not use ``send_id`` which is part of the example. Please let us know if that is important and we can look at how to implement it.

**Comment by themightychris** [comment]
@acouch Heads up—switching to using a HubSpot template might lose the responsive design we have now. Responsive email templates aren't really feasible for non-devs to update effectively while maintaining high UX quality. It looks like the SMTP API option would let us keep using our own template—if that's desirable

**Comment by thekaveman** [comment]
Thanks for the update! We're [scheduling a meeting](https://cal-itp.slack.com/archives/C01CT346NDC/p1677105214411489?thread_ts=1677100345.542039&cid=C01CT346NDC) to talk through some of these options.

**Comment by AnthonyRollins** [comment]
@charlie-costanzo Sending the `emailID` to you as a direct message on Slack.

**Comment by AnthonyRollins** [comment]
@charlie-costanzo I've imported the contacts list into Hubspot and then exported the list, which includes `Hubspot-Record-ID` and `ITP_ID`. Here's the [exported list](https://docs.google.com/spreadsheets/d/18WOfYisjRXcQMlBuuS0xIPf5a24OxaFT-0x-RKaBhtk/edit#gid=0). @o-ram @edasmalchi I want to confirm everything in this list is correct.
