### ISSUE TITLE
investigate mixed http & https in site

### ISSUE THREAD

**Issue by machow** [cal-itp/reports#23]
I don't see any links using http in the feature branch, so wonder if it was from the earlier deploy?

**Comment by machow** [comment]
Could also be that they are hard-coded into agencies.yml?

**Comment by thekaveman** [comment]
No worries here @machow, I think this was from an old deploy and the issue has been fixed. Here's the deploy log output from the affected deploy:

```
```

**Comment by machow** [comment]
Ah, that'll do it--thanks!
