### ISSUE TITLE
Move GTFS file checks into own warehouse view named reports_file_checks

### ISSUE THREAD

**Issue by machow** [cal-itp/reports#38]
Currently our report calculates some daily feed file checks manually. However, it would be nice to move this calculation into its own view.

Our [daily feed file view](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/gtfs_schedule_fact_daily_feed_files.sql) stores 1 row per day, per observed file in data feed. For example, there might be a row saying AC Transit had a `agencies.txt` file on a given day.

The table can be queried like so:

```python
from calitp.tables import tbl
from siuba import *

tbl.views.gtfs_schedule_fact_daily_feed_files()
```

Here's the relevant section of the notebook:

![image](https://user-images.githubusercontent.com/2574498/135671348-6b05f47b-5f00-4867-a258-3a0584c0e56f.png)

## Add interpolated files to `tbl.views.gtfs_schedule_fact_daily_feed_files()`

[view file](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/gtfs_schedule_fact_daily_feed_files.sql)

* intermediate column marking next observed date
* join by a date range so that missing days are essentially forward filled with date x file name
* create is_interpolated column
* let's have only date and feed_key and file be non-null (**edit:**  non-null for interpolated columns. e.g. interpolated columns should be NULL for is_changed)

## View details

* name: `reports_weekly_file_checks`
* schema
  - date (this is the day corresponding to the start of a given week)
  - file_name
  - is_biweekly (let's chat about this after initial pass)

**Comment by acouch** [comment]
Closing as this is no longer relevant.
