### ISSUE TITLE
September report not showing a file check for the 19th

### ISSUE THREAD

**Issue by machow** [cal-itp/reports#41]
![image](https://user-images.githubusercontent.com/2574498/136828038-b82f7d19-9006-4b9d-b20a-febf8c13e8a0.png)

As it turns out, Sep 19th was the one day our downloader failed.. 

Should be resolved by this PR, which adds interpolated file data for every day (even when the downloader fails): https://github.com/cal-itp/data-infra/pull/430

**Comment by holly-g** [comment]
https://github.com/cal-itp/data-infra/pull/430 has been merged; looks like we can close this.
