### ISSUE TITLE
Refactor validation error section in report template

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/reports#51]
Please refactor the validation errors section of the report as follows:

- Add column headers `Error Name`, `Error Description`, `Number of Errors (YYYY-MM-DD)`
- Replace individual error descriptions with count of error type
- Do not show 3rd column in months with just 2 columns to report

<img width="1257" alt="Screen Shot 2021-12-03 at 12 10 06 PM-markup" src="https://user-images.githubusercontent.com/3112493/144673441-7fa3a5e5-7d72-42fd-a2da-190a8eb9c361.png">

**Comment by machow** [comment]
Hey--want to double check I understand. Are you saying each of the three date columns should be named like this?:

* 2021-08-01 becomes `Number of Errors (2021-08-01)`
* 2021-08-15 becomes `Number of Errors (2021-08-15)`
* 2021-08-29 becomes `Number of errors (2021-08-29)`

For checking these changes, here is a link to a page that currently has three date columns (the third is empty) that should only have 2: https://development-build--cal-itp-reports.netlify.app/gtfs_schedule/2021/11/4/index.html
