### ISSUE TITLE
Release December reports.calitp.org 

### ISSUE THREAD

**Issue by holly-g** [cal-itp/reports#57]
- [x] generate reports
- [x] push to development and sanity check
- [x] request a review from Olivia
- [ ] deploy reports by merging to main/publish the website to prod

**Comment by Nkdiaz** [comment]
On going documentation for end-to-end generation of December reports with various checks

1.  generate reports -[ ] done by evan
### Creating report data
``` 
pip install -r requirements
make generate_parameters
make all -j 30
```
sanity checks:
- [ ] verifying that parameters are generated in subfolders
- [ ] verify in outputs that reports were generated
- [ ] verify that data subfolder is present

2. Generate static site
``` 
npm run build
python -m http.server
```
sanity checks:

- [ ] report month has been added to UI
- [ ] find example of agency with no validation errors (avalon), with validation notices (santa clara), and with daily metric errors (sacrt)

3.  Request review from Olivia
4.  Deploy Reports 
to push report data to the production bucket
``` 
make sync-prod
```
or to copy from the dev to prod 
```
gsutil -m rsync -r -d gs://gtfs-data-test/report_gtfs_schedule/ gs://gtfs-data/report_gtfs_schedule/
```

- [ ] verify that production site has been updated with most up to date month

5. Email reports - Testing
obtain test emails from evan. verify with olivia and calitp that email contents are correct. Update the config file

- [ ] update config file to have current month

- [ ] verify from olivia that email content is correct
generate the template (if needed)
script execution in development
``` 
python 3_generate_report_emails.py development
```
- [ ] send out emails to evan's test.csv using sandbox token.
- [ ] send out emails to test.csv using production token
- [ ] verify that the emails pass visual inspection

6. Email reports - Prod
Once emails have passed visual inspection, change config file for production

``` 
python 3_generate_report_emails.py production 
```
pass prompt that asks if production is correct and verify email recipients are production
send out emails
7. verify emails successfully sent
- [ ]  verify in postmark that emails have been sent in the production server correctly and have not bounced etc.

**Comment by themightychris** [comment]
It's an odd flow that re-running the last github action on `main` _after_ pushing new reports data to the prod bucket is the way to get prod updated with the new report data. A minor improvement might be to augment the action to also support a `workflow_dispatch` trigger with an env input

**Comment by Nkdiaz** [comment]
December reports were sent out on 12-12-21
