### ISSUE TITLE
Lock main branch of this repo

### ISSUE THREAD

**Issue by machow** [cal-itp/reports#60]
@evansiroky do you mind adding branch protection to this repo, to disable pushing straight to main? Should be under: https://github.com/cal-itp/reports/settings/branches

**Comment by evansiroky** [comment]
I believe I have done this.

**Comment by machow** [comment]
ah thanks--looks locked down

![image](https://user-images.githubusercontent.com/2574498/145471740-1c60f7cb-63c3-435c-8e88-f56518ff1fda.png)
