### ISSUE TITLE
Allow users to search by agency name for GTFS Quality Reports 

### ISSUE THREAD

**Issue by Nkdiaz** [cal-itp/reports#79]
Currently for the monthly reports we display all the agencies alphabetically in a long list that the user has to scroll down and select. It would be a better user experience if the agencies are able to search at the top rather than have to scroll all the way down.![image](https://user-images.githubusercontent.com/32888103/152560132-b13f2926-8c4f-488e-b950-6fc3d5718905.png)

**Comment by ryon** [comment]
I'd like to accomplish this by adding [Alpine.js](https://alpinejs.dev/) to the front end. I can't currently build the project (I need updated data and/or access to GCP, as discussed in Slack), but here is a prototype:

## https://codepen.io/ryon/full/rNYWRep

<img width="730" alt="Screen Shot 2022-02-07 at 5 09 15 PM" src="https://user-images.githubusercontent.com/1154929/152880516-f753aa27-52da-4642-8047-61689eccfc75.png">
