### ISSUE TITLE
Enable Google Analytics for Monthly GTFS Reports

### ISSUE THREAD

**Issue by Nkdiaz** [cal-itp/reports#91]
As part of https://github.com/cal-itp/reports/pull/87, for the monthly GTFS Quality reports we have implemented link tracking to several parts of the mail to help inform analytics. To further implement we need to create a Google Tag Manager (GTM) and Google Analytics (GA) Account for Reports.Calitp.org. I will then need the embed code that I can then apply to the reports code.

**Comment by thekaveman** [comment]
Hello @Nkdiaz! I've added you to the Google Analytics property we have set up for the Reports site, with admin privileges.

I'm less familiar with the GTM stuff. Can you configure that through GA or is that something separate? Maybe we can grab some time to go over this on a screenshare.

**Comment by Nkdiaz** [comment]
@thekaveman No problem, now that I have access to GA I was able to set it up. Thanks!

**Comment by Nkdiaz** [comment]
Set up GA and GTM for the GTFS Quality reports
